version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shared-list"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d2cwf15to1mn"
s3_prefix = "shared-list"
region = "eu-north-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
